AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - Id: GlacierRule
          Prefix: glacier
          Status: Enabled
          ExpirationInDays: '365'
          Transitions:
            - TransitionInDays: '1'
              StorageClass: Glacier
      AccelerateConfiguration:
        AccelerationStatus: Enabled

  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "S3Bucket"
      PolicyDocument: !Sub |
        {
          "Id": "s3-secured-policy-arn:aws:s3:::${S3Bucket}",
          "Statement": [
            {
              "Sid": "DenyIncorrectEncryptionHeader",
              "Action": "s3:PutObject",
              "Effect": "Deny",
              "Resource": "arn:aws:s3:::${S3Bucket}/*",
              "Condition": { "StringNotEquals": { "s3:x-amz-server-side-encryption": "AES256" } },
              "Principal": { "AWS": "*"}
            },
            {
              "Sid": "DenyUnEncryptedObjectUploads",
              "Action": "s3:PutObject",
              "Effect": "Deny",
              "Resource": "arn:aws:s3:::${S3Bucket}/*",
              "Condition": { "Null": { "s3:x-amz-server-side-encryption": "true" } },
              "Principal": { "AWS": "*"}
            },
            {
              "Sid": "ForceSSLOnlyAccess",
              "Action": "s3:*",
              "Effect": "Deny",
              "Resource": "arn:aws:s3:::${S3Bucket}/*",
              "Condition": { "Bool": { "aws:SecureTransport": false } },
              "Principal": { "AWS": "*"}
            }
          ]
        }
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the sample Amazon S3 bucket.
